version: "2"

services:
  redis:
    image: quay.io/centos7/redis-5-centos7
    container_name: redis
    ports:
      - 6379:6379
    user: "1024"

  postgres:
    container_name: postgres
    image: quay.io/centos7/postgresql-13-centos7
    environment:
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_DATABASE: packit
    ports:
      - 5432:5432

  hardly:
    container_name: hardly
    build:
      context: .
      dockerfile: files/Containerfile
      args:
        SOURCE_BRANCH: main
    image: quay.io/packit/hardly:dev
    command: run_worker.sh
    depends_on:
      - redis
      - postgres
    ports:
      - 5678:5678
    environment:
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      APP: hardly.tasks
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: packit
      DISTGIT_URL: ${DISTGIT_URL}
      DISTGIT_NAMESPACE: ${DISTGIT_NAMESPACE}
      CELERY_RETRY_LIMIT: 0
      PUSHGATEWAY_ADDRESS: ""
    volumes:
      - ./hardly:/src/hardly:ro,z
      - ../ogr/ogr:/usr/local/lib/python3.10/site-packages/ogr:ro,z
      - ../packit/packit:/usr/local/lib/python3.10/site-packages/packit:ro,z
      - ../packit-service/packit_service:/usr/local/lib/python3.10/site-packages/packit_service:ro,z
      - ./secrets/${SERVICE}/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
      - ./secrets/${SERVICE}/dev/id_rsa.pub:/packit-ssh/id_rsa.pub:ro,z
      - ./secrets/${SERVICE}/dev/id_rsa:/packit-ssh/id_rsa:ro,z
    user: "1024"

  service:
    container_name: service
    image: quay.io/packit/packit-service
    command: run_httpd.sh
    depends_on:
      - redis
      - postgres
    ports:
      - 8443:8443
    environment:
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: packit
    volumes:
      - ../ogr/ogr:/usr/local/lib/python3.10/site-packages/ogr:ro,z
      - ../packit/packit:/usr/local/lib/python3.10/site-packages/packit:ro,z
      - ../packit-service/packit_service:/usr/local/lib/python3.10/site-packages/packit_service:ro,z
      - ../packit-service/alembic:/src/alembic:ro,z
      - ./secrets/${SERVICE}/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
      - ./secrets/${SERVICE}/dev/fullchain.pem:/secrets/fullchain.pem:ro,z
      - ./secrets/${SERVICE}/dev/privkey.pem:/secrets/privkey.pem:ro,z
    user: "1024"
